const mongoose = require('mongoose');

const gameSchema = new mongoose.Schema({
  app_id: { type: Number, default: 0 },
  name: { type: String, required: true },
  release_date: String,
  required_age: { type: Number, default: 0 },
  price: { type: Number, default: 0 },
  dlc_count: { type: Number, default: 0 },
  detailed_description: { type: String, default: '' },
  about_the_game: { type: String, default: '' },
  short_description: { type: String, default: '' },
  reviews: { type: String, default: '' },
  header_image: String,
  website: { type: String, default: '' },
  support_url: { type: String, default: '' },
  support_email: { type: String, default: '' },
  windows: { type: Boolean, default: false },
  mac: { type: Boolean, default: false },
  linux: { type: Boolean, default: false },
  metacritic_score: { type: Number, default: 0 },
  metacritic_url: { type: String, default: '' },
  achievements: { type: Number, default: 0 },
  recommendations: { type: Number, default: 0 },
  notes: { type: String, default: '' },
  supported_languages: [String],
  full_audio_languages: [String],
  packages: [mongoose.Schema.Types.Mixed],
  developers: [String],
  publishers: [String],
  categories: [String],
  genres: [String],
  screenshots: [String],
  movies: [mongoose.Schema.Types.Mixed],
  user_score: { type: Number, default: 0 },
  score_rank: { type: String, default: '' },
  positive: { type: Number, default: 0 },
  negative: { type: Number, default: 0 },
  estimated_owners: { type: String, default: '0 - 0' },
  average_playtime_forever: { type: Number, default: 0 },
  average_playtime_2weeks: { type: Number, default: 0 },
  median_playtime_forever: { type: Number, default: 0 },
  median_playtime_2weeks: { type: Number, default: 0 },
  discount: { type: Number, default: 0 },
  peak_ccu: { type: Number, default: 0 },
  tags: [String],
});

module.exports = mongoose.model('Game', gameSchema, 'games');